import { getPublishedArticles } from '../lib/articles'
import { services } from '../data/services'
import { caseStudies } from '../data/caseStudies'
import { absoluteUrl } from '../lib/seo'
import pageDates from '../data/page-dates.json'

// Rebuilt periodically so newly published CMS posts enter the sitemap.
export const revalidate = 300

/* Built from the live route data (services, caseStudies, published articles),
   never a hand-kept list, so a new service or post cannot be forgotten.

   lastModified comes from data/page-dates.json, the last git commit date of the
   files that render each route, generated by `npm run sitemap:dates`. It was
   previously `new Date()` on every entry, i.e. build time stamped on every URL.
   Where no date can be determined the field is omitted rather than invented.

   No `priority` and no `changefreq`: Google ignores both, and a hand-assigned
   priority says nothing a crawler will act on.

   /privacy and /terms are deliberately absent (decision D6). They stay
   indexable and footer-linked; they just are not worth a sitemap slot. */
function entry(url, route) {
  const d = pageDates[route]
  return { url, ...(d ? { lastModified: new Date(d) } : {}) }
}

export default async function sitemap() {
  const articles = await getPublishedArticles()

  const serviceEntries = services.map(s =>
    entry(absoluteUrl(`/services/${s.slug}`), '/services')
  )

  const caseStudyEntries = caseStudies.map(c =>
    entry(absoluteUrl(`/case-studies/${c.slug}`), '/case-study')
  )

  const articleEntries = articles.map(article => ({
    url: absoluteUrl(`/blog/${article.slug}`),
    // A real modification date beats the published date; omit if neither exists.
    ...(article.updatedAt || article.date
      ? { lastModified: new Date(article.updatedAt || article.date) }
      : {}),
  }))

  return [
    entry(absoluteUrl('/'), '/'),
    entry(absoluteUrl('/about'), '/about'),
    entry(absoluteUrl('/contact'), '/contact'),
    entry(absoluteUrl('/engagements'), '/engagements'),
    entry(absoluteUrl('/case-studies'), '/case-studies'),
    entry(absoluteUrl('/blog'), '/blog'),
    ...serviceEntries,
    ...caseStudyEntries,
    ...articleEntries,
  ]
}
